(module
  (func (export "i32_eq_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eq (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_eq_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eq (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_eq_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i32.eq (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_eq_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eq (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_eq_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (i32.eq (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_eq_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eq (local.get $a) (local.get $b))))
  (func (export "i32_eq_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i32.eq (local.get $a) (local.get $b)))))
  (func (export "i32_eq_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i32.eq (local.get $a) (local.get $b)))))
  (func (export "i32_eq_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eq (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i32_eq_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i32.eq (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i32_eq_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i32.eq (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i32_ne_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.ne (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_ne_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.ne (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_ne_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i32.ne (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_ne_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.ne (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_ne_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (i32.ne (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_ne_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.ne (local.get $a) (local.get $b))))
  (func (export "i32_ne_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i32.ne (local.get $a) (local.get $b)))))
  (func (export "i32_ne_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i32.ne (local.get $a) (local.get $b)))))
  (func (export "i32_ne_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.ne (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i32_ne_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i32.ne (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i32_ne_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i32.ne (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i32_lt_s_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.lt_s (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_lt_s_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.lt_s (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_lt_s_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i32.lt_s (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_lt_s_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.lt_s (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_lt_s_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (i32.lt_s (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_lt_s_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.lt_s (local.get $a) (local.get $b))))
  (func (export "i32_lt_s_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i32.lt_s (local.get $a) (local.get $b)))))
  (func (export "i32_lt_s_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i32.lt_s (local.get $a) (local.get $b)))))
  (func (export "i32_lt_s_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.lt_s (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i32_lt_s_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i32.lt_s (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i32_lt_s_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i32.lt_s (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i32_gt_s_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.gt_s (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_gt_s_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.gt_s (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_gt_s_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i32.gt_s (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_gt_s_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.gt_s (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_gt_s_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (i32.gt_s (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_gt_s_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.gt_s (local.get $a) (local.get $b))))
  (func (export "i32_gt_s_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i32.gt_s (local.get $a) (local.get $b)))))
  (func (export "i32_gt_s_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i32.gt_s (local.get $a) (local.get $b)))))
  (func (export "i32_gt_s_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.gt_s (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i32_gt_s_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i32.gt_s (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i32_gt_s_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i32.gt_s (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i32_le_s_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.le_s (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_le_s_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.le_s (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_le_s_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i32.le_s (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_le_s_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.le_s (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_le_s_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (i32.le_s (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_le_s_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.le_s (local.get $a) (local.get $b))))
  (func (export "i32_le_s_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i32.le_s (local.get $a) (local.get $b)))))
  (func (export "i32_le_s_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i32.le_s (local.get $a) (local.get $b)))))
  (func (export "i32_le_s_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.le_s (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i32_le_s_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i32.le_s (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i32_le_s_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i32.le_s (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i32_ge_s_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.ge_s (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_ge_s_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.ge_s (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_ge_s_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i32.ge_s (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_ge_s_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.ge_s (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_ge_s_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (i32.ge_s (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_ge_s_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.ge_s (local.get $a) (local.get $b))))
  (func (export "i32_ge_s_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i32.ge_s (local.get $a) (local.get $b)))))
  (func (export "i32_ge_s_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i32.ge_s (local.get $a) (local.get $b)))))
  (func (export "i32_ge_s_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.ge_s (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i32_ge_s_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i32.ge_s (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i32_ge_s_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i32.ge_s (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i32_lt_u_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.lt_u (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_lt_u_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.lt_u (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_lt_u_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i32.lt_u (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_lt_u_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.lt_u (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_lt_u_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (i32.lt_u (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_lt_u_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.lt_u (local.get $a) (local.get $b))))
  (func (export "i32_lt_u_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i32.lt_u (local.get $a) (local.get $b)))))
  (func (export "i32_lt_u_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i32.lt_u (local.get $a) (local.get $b)))))
  (func (export "i32_lt_u_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.lt_u (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i32_lt_u_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i32.lt_u (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i32_lt_u_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i32.lt_u (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i32_ge_u_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.ge_u (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_ge_u_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.ge_u (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_ge_u_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i32.ge_u (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_ge_u_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.ge_u (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_ge_u_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (i32.ge_u (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_ge_u_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.ge_u (local.get $a) (local.get $b))))
  (func (export "i32_ge_u_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i32.ge_u (local.get $a) (local.get $b)))))
  (func (export "i32_ge_u_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i32.ge_u (local.get $a) (local.get $b)))))
  (func (export "i32_ge_u_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.ge_u (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i32_ge_u_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i32.ge_u (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i32_ge_u_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i32.ge_u (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i64_eq_br_if") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i64.eq (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_eq_br_if_eqz") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i64.eq (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_eq_br_if_eqz2") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i64.eq (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_eq_if") (param $a i64) (param $b i64) (result i32) (if (result i32) (i64.eq (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_eq_if_eqz") (param $a i64) (param $b i64) (result i32) (if (result i32) (i32.eqz (i64.eq (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_eq_select") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i64.eq (local.get $a) (local.get $b))))
  (func (export "i64_eq_select_eqz") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i64.eq (local.get $a) (local.get $b)))))
  (func (export "i64_eq_select_wide") (param $a i64) (param $b i64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i64.eq (local.get $a) (local.get $b)))))
  (func (export "i64_eq_loop_direct") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i64.eq (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i64_eq_loop_eqz") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i64.eq (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i64_eq_br_if_unwind") (param $a i64) (param $b i64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i64.eq (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i64_ne_br_if") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i64.ne (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_ne_br_if_eqz") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i64.ne (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_ne_br_if_eqz2") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i64.ne (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_ne_if") (param $a i64) (param $b i64) (result i32) (if (result i32) (i64.ne (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_ne_if_eqz") (param $a i64) (param $b i64) (result i32) (if (result i32) (i32.eqz (i64.ne (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_ne_select") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i64.ne (local.get $a) (local.get $b))))
  (func (export "i64_ne_select_eqz") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i64.ne (local.get $a) (local.get $b)))))
  (func (export "i64_ne_select_wide") (param $a i64) (param $b i64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i64.ne (local.get $a) (local.get $b)))))
  (func (export "i64_ne_loop_direct") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i64.ne (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i64_ne_loop_eqz") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i64.ne (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i64_ne_br_if_unwind") (param $a i64) (param $b i64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i64.ne (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i64_lt_s_br_if") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i64.lt_s (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_lt_s_br_if_eqz") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i64.lt_s (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_lt_s_br_if_eqz2") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i64.lt_s (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_lt_s_if") (param $a i64) (param $b i64) (result i32) (if (result i32) (i64.lt_s (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_lt_s_if_eqz") (param $a i64) (param $b i64) (result i32) (if (result i32) (i32.eqz (i64.lt_s (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_lt_s_select") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i64.lt_s (local.get $a) (local.get $b))))
  (func (export "i64_lt_s_select_eqz") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i64.lt_s (local.get $a) (local.get $b)))))
  (func (export "i64_lt_s_select_wide") (param $a i64) (param $b i64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i64.lt_s (local.get $a) (local.get $b)))))
  (func (export "i64_lt_s_loop_direct") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i64.lt_s (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i64_lt_s_loop_eqz") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i64.lt_s (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i64_lt_s_br_if_unwind") (param $a i64) (param $b i64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i64.lt_s (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i64_gt_s_br_if") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i64.gt_s (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_gt_s_br_if_eqz") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i64.gt_s (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_gt_s_br_if_eqz2") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i64.gt_s (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_gt_s_if") (param $a i64) (param $b i64) (result i32) (if (result i32) (i64.gt_s (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_gt_s_if_eqz") (param $a i64) (param $b i64) (result i32) (if (result i32) (i32.eqz (i64.gt_s (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_gt_s_select") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i64.gt_s (local.get $a) (local.get $b))))
  (func (export "i64_gt_s_select_eqz") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i64.gt_s (local.get $a) (local.get $b)))))
  (func (export "i64_gt_s_select_wide") (param $a i64) (param $b i64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i64.gt_s (local.get $a) (local.get $b)))))
  (func (export "i64_gt_s_loop_direct") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i64.gt_s (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i64_gt_s_loop_eqz") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i64.gt_s (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i64_gt_s_br_if_unwind") (param $a i64) (param $b i64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i64.gt_s (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i64_le_s_br_if") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i64.le_s (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_le_s_br_if_eqz") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i64.le_s (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_le_s_br_if_eqz2") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i64.le_s (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_le_s_if") (param $a i64) (param $b i64) (result i32) (if (result i32) (i64.le_s (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_le_s_if_eqz") (param $a i64) (param $b i64) (result i32) (if (result i32) (i32.eqz (i64.le_s (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_le_s_select") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i64.le_s (local.get $a) (local.get $b))))
  (func (export "i64_le_s_select_eqz") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i64.le_s (local.get $a) (local.get $b)))))
  (func (export "i64_le_s_select_wide") (param $a i64) (param $b i64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i64.le_s (local.get $a) (local.get $b)))))
  (func (export "i64_le_s_loop_direct") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i64.le_s (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i64_le_s_loop_eqz") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i64.le_s (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i64_le_s_br_if_unwind") (param $a i64) (param $b i64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i64.le_s (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i64_ge_s_br_if") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i64.ge_s (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_ge_s_br_if_eqz") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i64.ge_s (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_ge_s_br_if_eqz2") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i64.ge_s (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_ge_s_if") (param $a i64) (param $b i64) (result i32) (if (result i32) (i64.ge_s (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_ge_s_if_eqz") (param $a i64) (param $b i64) (result i32) (if (result i32) (i32.eqz (i64.ge_s (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_ge_s_select") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i64.ge_s (local.get $a) (local.get $b))))
  (func (export "i64_ge_s_select_eqz") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i64.ge_s (local.get $a) (local.get $b)))))
  (func (export "i64_ge_s_select_wide") (param $a i64) (param $b i64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i64.ge_s (local.get $a) (local.get $b)))))
  (func (export "i64_ge_s_loop_direct") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i64.ge_s (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i64_ge_s_loop_eqz") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i64.ge_s (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i64_ge_s_br_if_unwind") (param $a i64) (param $b i64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i64.ge_s (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i64_lt_u_br_if") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i64.lt_u (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_lt_u_br_if_eqz") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i64.lt_u (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_lt_u_br_if_eqz2") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i64.lt_u (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_lt_u_if") (param $a i64) (param $b i64) (result i32) (if (result i32) (i64.lt_u (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_lt_u_if_eqz") (param $a i64) (param $b i64) (result i32) (if (result i32) (i32.eqz (i64.lt_u (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_lt_u_select") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i64.lt_u (local.get $a) (local.get $b))))
  (func (export "i64_lt_u_select_eqz") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i64.lt_u (local.get $a) (local.get $b)))))
  (func (export "i64_lt_u_select_wide") (param $a i64) (param $b i64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i64.lt_u (local.get $a) (local.get $b)))))
  (func (export "i64_lt_u_loop_direct") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i64.lt_u (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "i64_lt_u_loop_eqz") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i64.lt_u (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "i64_lt_u_br_if_unwind") (param $a i64) (param $b i64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i64.lt_u (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f32_eq_br_if") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (f32.eq (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_eq_br_if_eqz") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (f32.eq (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_eq_br_if_eqz2") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f32.eq (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_eq_if") (param $a f32) (param $b f32) (result i32) (if (result i32) (f32.eq (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_eq_if_eqz") (param $a f32) (param $b f32) (result i32) (if (result i32) (i32.eqz (f32.eq (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_eq_select") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (f32.eq (local.get $a) (local.get $b))))
  (func (export "f32_eq_select_eqz") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f32.eq (local.get $a) (local.get $b)))))
  (func (export "f32_eq_select_wide") (param $a f32) (param $b f32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f32.eq (local.get $a) (local.get $b)))))
  (func (export "f32_eq_loop_direct") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f32.eq (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f32_eq_loop_eqz") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f32.eq (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f32_eq_br_if_unwind") (param $a f32) (param $b f32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f32.eq (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f32_ne_br_if") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (f32.ne (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_ne_br_if_eqz") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (f32.ne (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_ne_br_if_eqz2") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f32.ne (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_ne_if") (param $a f32) (param $b f32) (result i32) (if (result i32) (f32.ne (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_ne_if_eqz") (param $a f32) (param $b f32) (result i32) (if (result i32) (i32.eqz (f32.ne (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_ne_select") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (f32.ne (local.get $a) (local.get $b))))
  (func (export "f32_ne_select_eqz") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f32.ne (local.get $a) (local.get $b)))))
  (func (export "f32_ne_select_wide") (param $a f32) (param $b f32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f32.ne (local.get $a) (local.get $b)))))
  (func (export "f32_ne_loop_direct") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f32.ne (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f32_ne_loop_eqz") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f32.ne (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f32_ne_br_if_unwind") (param $a f32) (param $b f32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f32.ne (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f32_lt_br_if") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (f32.lt (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_lt_br_if_eqz") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (f32.lt (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_lt_br_if_eqz2") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f32.lt (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_lt_if") (param $a f32) (param $b f32) (result i32) (if (result i32) (f32.lt (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_lt_if_eqz") (param $a f32) (param $b f32) (result i32) (if (result i32) (i32.eqz (f32.lt (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_lt_select") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (f32.lt (local.get $a) (local.get $b))))
  (func (export "f32_lt_select_eqz") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f32.lt (local.get $a) (local.get $b)))))
  (func (export "f32_lt_select_wide") (param $a f32) (param $b f32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f32.lt (local.get $a) (local.get $b)))))
  (func (export "f32_lt_loop_direct") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f32.lt (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f32_lt_loop_eqz") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f32.lt (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f32_lt_br_if_unwind") (param $a f32) (param $b f32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f32.lt (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f32_gt_br_if") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (f32.gt (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_gt_br_if_eqz") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (f32.gt (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_gt_br_if_eqz2") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f32.gt (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_gt_if") (param $a f32) (param $b f32) (result i32) (if (result i32) (f32.gt (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_gt_if_eqz") (param $a f32) (param $b f32) (result i32) (if (result i32) (i32.eqz (f32.gt (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_gt_select") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (f32.gt (local.get $a) (local.get $b))))
  (func (export "f32_gt_select_eqz") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f32.gt (local.get $a) (local.get $b)))))
  (func (export "f32_gt_select_wide") (param $a f32) (param $b f32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f32.gt (local.get $a) (local.get $b)))))
  (func (export "f32_gt_loop_direct") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f32.gt (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f32_gt_loop_eqz") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f32.gt (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f32_gt_br_if_unwind") (param $a f32) (param $b f32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f32.gt (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f32_le_br_if") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (f32.le (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_le_br_if_eqz") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (f32.le (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_le_br_if_eqz2") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f32.le (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_le_if") (param $a f32) (param $b f32) (result i32) (if (result i32) (f32.le (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_le_if_eqz") (param $a f32) (param $b f32) (result i32) (if (result i32) (i32.eqz (f32.le (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_le_select") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (f32.le (local.get $a) (local.get $b))))
  (func (export "f32_le_select_eqz") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f32.le (local.get $a) (local.get $b)))))
  (func (export "f32_le_select_wide") (param $a f32) (param $b f32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f32.le (local.get $a) (local.get $b)))))
  (func (export "f32_le_loop_direct") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f32.le (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f32_le_loop_eqz") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f32.le (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f32_le_br_if_unwind") (param $a f32) (param $b f32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f32.le (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f32_ge_br_if") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (f32.ge (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_ge_br_if_eqz") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (f32.ge (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_ge_br_if_eqz2") (param $a f32) (param $b f32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f32.ge (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f32_ge_if") (param $a f32) (param $b f32) (result i32) (if (result i32) (f32.ge (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_ge_if_eqz") (param $a f32) (param $b f32) (result i32) (if (result i32) (i32.eqz (f32.ge (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f32_ge_select") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (f32.ge (local.get $a) (local.get $b))))
  (func (export "f32_ge_select_eqz") (param $a f32) (param $b f32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f32.ge (local.get $a) (local.get $b)))))
  (func (export "f32_ge_select_wide") (param $a f32) (param $b f32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f32.ge (local.get $a) (local.get $b)))))
  (func (export "f32_ge_loop_direct") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f32.ge (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f32_ge_loop_eqz") (param $a f32) (param $b f32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f32.ge (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f32_ge_br_if_unwind") (param $a f32) (param $b f32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f32.ge (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f64_eq_br_if") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (f64.eq (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_eq_br_if_eqz") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (f64.eq (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_eq_br_if_eqz2") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f64.eq (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_eq_if") (param $a f64) (param $b f64) (result i32) (if (result i32) (f64.eq (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_eq_if_eqz") (param $a f64) (param $b f64) (result i32) (if (result i32) (i32.eqz (f64.eq (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_eq_select") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (f64.eq (local.get $a) (local.get $b))))
  (func (export "f64_eq_select_eqz") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f64.eq (local.get $a) (local.get $b)))))
  (func (export "f64_eq_select_wide") (param $a f64) (param $b f64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f64.eq (local.get $a) (local.get $b)))))
  (func (export "f64_eq_loop_direct") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f64.eq (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f64_eq_loop_eqz") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f64.eq (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f64_eq_br_if_unwind") (param $a f64) (param $b f64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f64.eq (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f64_ne_br_if") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (f64.ne (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_ne_br_if_eqz") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (f64.ne (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_ne_br_if_eqz2") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f64.ne (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_ne_if") (param $a f64) (param $b f64) (result i32) (if (result i32) (f64.ne (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_ne_if_eqz") (param $a f64) (param $b f64) (result i32) (if (result i32) (i32.eqz (f64.ne (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_ne_select") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (f64.ne (local.get $a) (local.get $b))))
  (func (export "f64_ne_select_eqz") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f64.ne (local.get $a) (local.get $b)))))
  (func (export "f64_ne_select_wide") (param $a f64) (param $b f64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f64.ne (local.get $a) (local.get $b)))))
  (func (export "f64_ne_loop_direct") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f64.ne (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f64_ne_loop_eqz") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f64.ne (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f64_ne_br_if_unwind") (param $a f64) (param $b f64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f64.ne (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f64_lt_br_if") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (f64.lt (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_lt_br_if_eqz") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (f64.lt (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_lt_br_if_eqz2") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f64.lt (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_lt_if") (param $a f64) (param $b f64) (result i32) (if (result i32) (f64.lt (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_lt_if_eqz") (param $a f64) (param $b f64) (result i32) (if (result i32) (i32.eqz (f64.lt (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_lt_select") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (f64.lt (local.get $a) (local.get $b))))
  (func (export "f64_lt_select_eqz") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f64.lt (local.get $a) (local.get $b)))))
  (func (export "f64_lt_select_wide") (param $a f64) (param $b f64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f64.lt (local.get $a) (local.get $b)))))
  (func (export "f64_lt_loop_direct") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f64.lt (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f64_lt_loop_eqz") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f64.lt (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f64_lt_br_if_unwind") (param $a f64) (param $b f64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f64.lt (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f64_gt_br_if") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (f64.gt (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_gt_br_if_eqz") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (f64.gt (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_gt_br_if_eqz2") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f64.gt (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_gt_if") (param $a f64) (param $b f64) (result i32) (if (result i32) (f64.gt (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_gt_if_eqz") (param $a f64) (param $b f64) (result i32) (if (result i32) (i32.eqz (f64.gt (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_gt_select") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (f64.gt (local.get $a) (local.get $b))))
  (func (export "f64_gt_select_eqz") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f64.gt (local.get $a) (local.get $b)))))
  (func (export "f64_gt_select_wide") (param $a f64) (param $b f64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f64.gt (local.get $a) (local.get $b)))))
  (func (export "f64_gt_loop_direct") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f64.gt (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f64_gt_loop_eqz") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f64.gt (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f64_gt_br_if_unwind") (param $a f64) (param $b f64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f64.gt (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f64_le_br_if") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (f64.le (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_le_br_if_eqz") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (f64.le (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_le_br_if_eqz2") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f64.le (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_le_if") (param $a f64) (param $b f64) (result i32) (if (result i32) (f64.le (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_le_if_eqz") (param $a f64) (param $b f64) (result i32) (if (result i32) (i32.eqz (f64.le (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_le_select") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (f64.le (local.get $a) (local.get $b))))
  (func (export "f64_le_select_eqz") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f64.le (local.get $a) (local.get $b)))))
  (func (export "f64_le_select_wide") (param $a f64) (param $b f64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f64.le (local.get $a) (local.get $b)))))
  (func (export "f64_le_loop_direct") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f64.le (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f64_le_loop_eqz") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f64.le (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f64_le_br_if_unwind") (param $a f64) (param $b f64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f64.le (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "f64_ge_br_if") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (f64.ge (local.get $a) (local.get $b))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_ge_br_if_eqz") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (f64.ge (local.get $a) (local.get $b)))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_ge_br_if_eqz2") (param $a f64) (param $b f64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (f64.ge (local.get $a) (local.get $b))))) (return (i32.const 1))) (i32.const 0))
  (func (export "f64_ge_if") (param $a f64) (param $b f64) (result i32) (if (result i32) (f64.ge (local.get $a) (local.get $b)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_ge_if_eqz") (param $a f64) (param $b f64) (result i32) (if (result i32) (i32.eqz (f64.ge (local.get $a) (local.get $b))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "f64_ge_select") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (f64.ge (local.get $a) (local.get $b))))
  (func (export "f64_ge_select_eqz") (param $a f64) (param $b f64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (f64.ge (local.get $a) (local.get $b)))))
  (func (export "f64_ge_select_wide") (param $a f64) (param $b f64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (f64.ge (local.get $a) (local.get $b)))))
  (func (export "f64_ge_loop_direct") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (f64.ge (local.get $a) (local.get $b)))))) (local.get $n))
  (func (export "f64_ge_loop_eqz") (param $a f64) (param $b f64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (f64.ge (local.get $a) (local.get $b))))))) (local.get $n))
  (func (export "f64_ge_br_if_unwind") (param $a f64) (param $b f64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (f64.ge (local.get $a) (local.get $b)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i32_eqz_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (local.get $a))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_eqz_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (local.get $a)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_eqz_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i32.eqz (local.get $a))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_eqz_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (local.get $a)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_eqz_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (i32.eqz (local.get $a))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_eqz_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (local.get $a))))
  (func (export "i32_eqz_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i32.eqz (local.get $a)))))
  (func (export "i32_eqz_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i32.eqz (local.get $a)))))
  (func (export "i32_eqz_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (local.get $a)))))) (local.get $n))
  (func (export "i32_eqz_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i32.eqz (local.get $a))))))) (local.get $n))
  (func (export "i32_eqz_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i32.eqz (local.get $a)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i64_eqz_br_if") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i64.eqz (local.get $a))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_eqz_br_if_eqz") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i64.eqz (local.get $a)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_eqz_br_if_eqz2") (param $a i64) (param $b i64) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (i64.eqz (local.get $a))))) (return (i32.const 1))) (i32.const 0))
  (func (export "i64_eqz_if") (param $a i64) (param $b i64) (result i32) (if (result i32) (i64.eqz (local.get $a)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_eqz_if_eqz") (param $a i64) (param $b i64) (result i32) (if (result i32) (i32.eqz (i64.eqz (local.get $a))) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i64_eqz_select") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i64.eqz (local.get $a))))
  (func (export "i64_eqz_select_eqz") (param $a i64) (param $b i64) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (i64.eqz (local.get $a)))))
  (func (export "i64_eqz_select_wide") (param $a i64) (param $b i64) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (i64.eqz (local.get $a)))))
  (func (export "i64_eqz_loop_direct") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i64.eqz (local.get $a)))))) (local.get $n))
  (func (export "i64_eqz_loop_eqz") (param $a i64) (param $b i64) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (i64.eqz (local.get $a))))))) (local.get $n))
  (func (export "i64_eqz_br_if_unwind") (param $a i64) (param $b i64) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (i64.eqz (local.get $a)) (br_if $b) (drop) (drop) (i32.const 0)))
  (func (export "i32_plain_br_if") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (local.get $a)) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_plain_br_if_eqz") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (local.get $a))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_plain_br_if_eqz2") (param $a i32) (param $b i32) (result i32) (block $b (br_if $b (i32.eqz (i32.eqz (local.get $a)))) (return (i32.const 1))) (i32.const 0))
  (func (export "i32_plain_if") (param $a i32) (param $b i32) (result i32) (if (result i32) (local.get $a) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_plain_if_eqz") (param $a i32) (param $b i32) (result i32) (if (result i32) (i32.eqz (local.get $a)) (then (i32.const 1)) (else (i32.const 0))))
  (func (export "i32_plain_select") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (local.get $a)))
  (func (export "i32_plain_select_eqz") (param $a i32) (param $b i32) (result i32) (select (i32.const 1) (i32.const 0) (i32.eqz (local.get $a))))
  (func (export "i32_plain_select_wide") (param $a i32) (param $b i32) (result i32) (i32.wrap_i64 (select (i64.const 1) (i64.const 0) (local.get $a))))
  (func (export "i32_plain_loop_direct") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (local.get $a))))) (local.get $n))
  (func (export "i32_plain_loop_eqz") (param $a i32) (param $b i32) (result i32) (local $n i32) (loop $l (local.set $n (i32.add (local.get $n) (i32.const 1))) (if (i32.sub (i32.const 2) (local.get $n)) (then (br_if $l (i32.eqz (local.get $a)))))) (local.get $n))
  (func (export "i32_plain_br_if_unwind") (param $a i32) (param $b i32) (result i32) (block $b (result i32) (i32.const 1) (i32.const 7) (local.get $a) (br_if $b) (drop) (drop) (i32.const 0)))
)
